//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет оставшегося времени.
    /// </summary>
    // *** Start programmer edit section *** (РасчетОстВрем CustomAttributes)

    // *** End programmer edit section *** (РасчетОстВрем CustomAttributes)
    [AutoAltered()]
    [Caption("Расчет оставшегося времени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетОстВремE", new string[] {
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    [AssociatedDetailViewAttribute("РасчетОстВремE", "ОказКонсульт", "ОказКонсультE", true, "", "Оказ консульт", true, new string[] {
            ""})]
    [View("РасчетОстВремL", new string[] {
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    public class РасчетОстВрем : ICSSoft.STORMNET.DataObject
    {
        
        private int fИспользовано;
        
        private int fДоступно;
        
        private IIS.Kursovaya12.DetailArrayOfОказКонсульт fОказКонсульт;
        
        // *** Start programmer edit section *** (РасчетОстВрем CustomMembers)

        // *** End programmer edit section *** (РасчетОстВрем CustomMembers)

        
        /// <summary>
        /// Доступно.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)
        public virtual int Доступно
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get start)
                int result = this.fДоступно;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set start)
                this.fДоступно = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set end)
            }
        }
        
        /// <summary>
        /// Использовано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)
        public virtual int Использовано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get start)
                int result = this.fИспользовано;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set start)
                this.fИспользовано = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set end)
            }
        }
        
        /// <summary>
        /// Расчет оставшегося времени.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсульт CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.ОказКонсульт CustomAttributes)
        public virtual IIS.Kursovaya12.DetailArrayOfОказКонсульт ОказКонсульт
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсульт Get start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсульт Get start)
                if ((this.fОказКонсульт == null))
                {
                    this.fОказКонсульт = new IIS.Kursovaya12.DetailArrayOfОказКонсульт(this);
                }
                IIS.Kursovaya12.DetailArrayOfОказКонсульт result = this.fОказКонсульт;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсульт Get end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсульт Set start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсульт Set start)
                this.fОказКонсульт = value;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсульт Set end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсульт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетОстВремE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремE", typeof(IIS.Kursovaya12.РасчетОстВрем));
                }
            }
            
            /// <summary>
            /// "РасчетОстВремL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремL", typeof(IIS.Kursovaya12.РасчетОстВрем));
                }
            }
        }
    }
}
